baseURL = "https://fm22tactics.com"
languageCode = "en-us"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
theme = "hugo-winston"
themesDir = "../.."
title = "FM22 Tactics"
[[menu.main]]
name = "Buy FM22"
url = "https://beta.fm-base.co.uk/buy-fm22"
weight = 3
[module.hugoVersion]
extended = true
min = "0.55.0"
[params]
addDot = true
addFrame = true
google_analytics_id = "G-YC5KQB77MM"
showAuthorOnHomepage = false
showAuthorOnPosts = false
showPostsOnHomepage = false
twitter_handle = "@fmbase"
